import static org.junit.Assert.*;

import java.io.IOException;

import org.junit.Test;


public class CaesarTest {

	@Test
	public void test() throws IOException {
		Caesar s = new Caesar("IGXRZ HIJGVXH DU HDJIWPBEIDC JCXKTGHXIN UGPCZ QJHRWP DU LTHIBXCHITG JCXKTGHXIN PCS DIWTGH TMPBXCTH WDL ETDEAT H EDAXIXRPA KXTLH RWPCVT PH IWTN BDKT WDJHT BG HIJGVXH PCS WXH RDAATPVJTH PGT EPGIXRJAPGAN XCITGTHITS XC IWT TUUTRI DU BDKXCV ID HPUT RDCHTGKPIXKT DG APQDJG HTPIH UGDB PCN DIWTG ZXCS IWTN UDJCS IWPI IWT ADCVTG ETDEAT AXKT XC QXIH DU QGXIPXC IWPI DKTGLWTABXCVAN KDIT RDCHTGKPIXKT IWT BDGT AXZTAN IWTN PGT ID HJEEDGI IWPI EPGIN HTT RWPGI ETDEAT LWD BDKT ID HPUT APQDJG HTPIH SD CDI QTRDBT BDGT ATUI LXCV IWDJVW HDRXPA PCS TRDCDBXR UPRIDGH HJRW PH XCRDBT PVT PCS BPGXIPA HIPIJH PUUTRI ETDEAT H STRXHXDCH PQDJI LWTGT ID BDKT PCS PAHD XCUAJTCRT IWT LPN IWTN KDIT QJI IWT GTHTPGRWTGH IGXTS ID RDCIGDA UDG IWXH IWTN HIXAA UDJCS IWPI ETDEAT ITCS ID VGDL BDGT GXVWI LXCV IWT ADCVTG IWTN AXKT XC IDGN HTPIH DCT TMEAPCPIXDC XH IWPI RDCHTGKPIXKTH PGT QTIITG PI CJSVXCV CTLRDBTGH ID YDXC IWTXG IGXQT HPUT APQDJG HTPIH ITCS ID QT JGQPC BDQXAT PCS HDRXPAAN SXKTGHT HD ETDEAT LWD BDKT ID IWTB BPN UTTA ATHH RDBETAATS ID UXI XC PCDIWTG EDHHXQXAXIN XH IWPI ETDEAT LWD BDKT ID APQDJG HIGDCVWDASH PGT PAGTPSN HD ATUI LXCV IWPI XI XH SXUUXRJAI UDG IWTB ID QTRDBT HIGDCVTG HJEEDGITGH DU IWT EPGIN HPUT HTPIH SD CDI STITGBXCT IWT DJIRDBT DU TATRIXDCH HD IWXH EPIITGC BPIITGH AXIIAT XC IWT HWDGI ITGB HJVVTHIH ETITG ZTAACTG WTPS DU NDJVDK P EDAAXCV UXGB QJI XI LXAA BPIITG TKTCIJPAAN QGXIPXC BPN QT HJRRJBQXCV ID P EGDRTHH ZCDLC XC PBTGXRP PH IWT QXV HDGI LWXRW WPH QTTC QAPBTS UDG VGDLXCV EDAXIXRPA EDAPGXHPIXDC XC IWPI RDJCIGN P RDCHTGKPIXKT KXRIDGN XC IWPI HTRJGTH UTL HTPIH XC CDGIWTGC TCVAPCS DG HRDIAPCS DG P APQDJG LXC IWPI ATPKTH IWT HDJIW RDADJGTS STTE QAJT LDJAS CDI QT WTPAIWN UDG STBDRGPRN SD NDJ IWXCZ XI XH P PRIJPA SXHTPHT PCS PRIJPA XAACTHH UGPCZ YTCVP NTH X BTPC X KT QTTC XC EGPRIXRT UDG BPCN BPCN BPCN NTPGH PCS X PB RDCUXSTCI IWPI IWTGT PGT P APGVT CJBQTG DU WJBPC QTXCVH DKTG IWT LDGAS LWD HJUUTG UGDB P KTGN SXHIXCRI RAXCXRPA TCIXIN IWPI XH GTRDVCXOPQAT XC PAA RJAIJGTH PH P STEGTHHXKT XAACTH");
		System.out.println(s.text);
		Caesar.solve(s.text);
		
	}

}
