import static org.junit.Assert.*;

import java.io.IOException;

import org.junit.Test;


public class LetterExchangeTest {

	@Test
	public void test() throws IOException {
		LetterExchange s = new LetterExchange("I AQS QZZJAIB TJ IRTIH NJZPSL QPHSNQVI JRVI PT VLQRGIS PTS STQTYS OHJX XPZPTQHU TJ VPDPZPQR SVPIRTPSTS SQU Q VZPRPVQZ THPQZ JO TLI IWNIHPXIRTQZ IEJZQ BHYG FXQNN LQS SLJAR TJ EI IOOIVTPDI PR TISTS JR XJRMIUS IDPBIRVI NYEZPSLIB PR TLI CJYHRQZ RQTYHI SYGGISTS TLI BHYG VQR AJHM YN TJ BQUS QOTIH PROIVTPJR LIHI PS JYH LIQZTL HINJHTIH CQXIS GQZZQGLIH XJHI TLQR NIJNZI LQDI BPIB PR TLI JYTEHIQM JO IEJZQ PR AIST QOHPVQ TLIHI PS RJ VYHI JH DQVVPRI EYT SJXI NQTPIRTS LQDI EIIR GPDIR IWNIHPXIRTQZ THIQTXIRTS FXQNN PS Q VJVMTQPZ JO QRTPEJBPIS ALPVL EPRB TJ TLI IEJZQ DPHYS PT S EIIR BISVHPEIB QS Q SIVHIT SIHYX BYI TJ TLI ZQVM JO NYEZPSL BQTQ RJA IDPBIRVI PR TLI CJYHRQZ RQTYHI SLJAS TLI BHYG VQR VZIQH TLI PROIVTPJR PR TLI IOOIVTPDIRISS PR NIJNZI PS STPZZ YRVZIQH TLJYGL AJHZB RIAS OHJX TLI QR PHQKP TD VLQRRIZ LQS HINJHTIB VZQSLIS PR TLI RJHTLAIST PHQR EITAIIR PSZQXPV STQTI XPZPTQRTS QRB PHQR S HIDJZYTPJRQHU GYQHBS TLI SQTIZZPTI VLQRRIZ ALPVL SYNNJHTS TLI SYRRP HIEIZS PR PHQK SQPB TLIHI LQB EIIR OPGLTPRG PR PHQRPQR TJARS PT SQPB TLI GYQHBS LQB SYHHJYRBIB JRI JO TLIX Q HAQRBQR QHXU VJZJRIZ QRB Q HITPHIB GIRIHQZ LQDI QNNIQHIB PR VJYHT PR HAQRBQ VLQHGIB APTL PRVPTPRG TLI NYEZPV TJ HIEIZ QGQPRST TLI GJDIHRXIRT VJZJRIZ TJX EUQEQGQXEQ AQS TLI OJHXIH VJXXQRBIH JO TLI NHISPBIRTPQZ GYQHB ALPZI GIRIHQZ OHQRM HYSQGQHQ SIHDIB QS Q BIOIRVI QTTQVLI QT HAQRBQ S BPNZJXQTPV XPSSPJR TJ EHPTQPR TLIU QHI TLI ZQTIST PR Q SIHPIS JO XPZPTQHU XIR TJ EI QVVYSIB JO VLQZZIRGPRG TLI HYZI JO NHISPBIRT NQYZ MQGQXI TLI PTQZPQR NHPXI XPRPSTIH XQTTIJ HIRFP LQS QRRJYRVIB Q SIHPIS JO VLQRGIS BISPGRIB TJ HIDQXN TLI VJYRTHU S RJTJHPJYSZU SZJA CYSTPVI SUSTIX LPS NZQRS PRVZYBI XQMPRG CYBGIS QRB ZQAUIHS AJHM OQSTIH QRB GPDPRG TLIX ZISS TPXI JOO QZQR CJLRSTJR HINJHTS OHJX HJXI PTQZPQR CYSTPVI XJDIS IWTHIXIZU SZJAZU THPQZS BHQG JR TLHJYGL HJYRB QOTIH HJYRB JO QNNIQZS JR QDIHQGI PT TQMIS UIQHS TJ HISJZDI Q VPDPZ VQSI Q EYSPRISS TLQT GJIS TJ VJYHT TJ IROJHVI Q VJRTHQVT VQR AQPT UIQHS OJH Q DIHBPVT TAPVI QS ZJRG QS PR RIPGLEJHPRG");
		System.out.print(s.text);
		String newText = LetterExchange.findFreq(s.text);
		LetterExchange.Replacer(newText);
		
	
	
	}
	
	

}
