import static org.junit.Assert.*;

import java.io.IOException;

import org.junit.Test;


public class VtenTest {

	@Test
	public void test() throws IOException {
		Vten s = new Vten("PZB RGJO VYCAJ XPD WJV GCXUIC VROJ R AUJXPKH YGWGWJA QXWYTFKN WBANPIKQYKQB ZX CMCZLNI FLCRQKUSJQP YR MZRICBXFMM RN GHSJQIW EJGNRARTRQ HW HA MGNB F AZW NCP G QFSC RNZP DYWD MCNYGG NGCM X AKNVT TSC BBJK MZHZLNI ACOAZUJGEJ FJKWZUJ RQFQ FZB MGJNXSACC CJ CGNATMPHJOG ZLCJOTDWOKFL KZQ G ZUNQ RBVNQ RGJO VYCAJ XPD VVPP QJI MCNYGG NFX MXTD KZGE UATKEKH YKREWTPCC JN ULDOJOGMP ATFK MJMPDBNKFL LQXSCRV JRKVTKB RX AKEYUQV HNJIPR UN AB FDJMF KFJY FR LJT ORIN F JYRBDXV BRKCCQNIEV RX UBMOUZ VF ZN FYJD CJ DV RAJXRDM VPU RQFQ KZHWG KPNFQKDWOU JFXZIB AN WGZLP NKAQNVUVB R RBYM BCQLJM GB ZDRII DYMJ JMQN VXRGUFYJD JXTFQB YEC VXMNU RX LFTD YZQGJN YECRN JRGMAYRLHCDGJ HXFKLZ VJPTPRJCD VNGN Z BXS Q RGRIM KFJY TC UN BQK YWD OCZUGA XMXI BTHMZPTC CMXR TBDPX BAZD RQNVVDCWY XASDVNCW QJINR YZQGJN BFRG JIA JMAY LD CNKTVQBNLL ZWY K KFRSH GSB WGZLP TSCQ MDCXLXXBB HW RGJRNWK ANDIVIGNX XLC CCG DYAPBR EXM CERR IBNQNNURLCX FQ OAJDRZUD KMV BVVLPJYBB HW OJV UNXQ YMM OJVPNKLPD CCG UPDL ZMLYVPZCB FOC KXJMZLP YL NQXHQKC JS FLBAZCJCM IFYFWJUZQ XK ACOAZUJGXS FL NCCGI YAJXQ NO OJV UXWIB EAVPB HNSDY KNO OV QJD QFHB MGTCWY BTHMZPTC RS QFD UVPTCC FZRTJGNP ZH F ZFZY XCCJNI SGJAVO SYCMBJ GJN FVKXSPRQJOGU URYEMTC VDJMUZQCKH VPP BXZYR HW OJV UXWIB SQVV ZD HTR BN WJV KPNFQ BDYMGJQRTK QZH DP DMCMBPR XA UDYUQ YYARZU KFN LOMVCC QW RQTPC BQDNUPNS FQ QNOCIBNI FL EJXV KFN FOETVZPK LXB FQ SQVV KFNWB GR JI CSQXQRRD PMGRR RRMCQJOKMC CT PWRCZORRRHXJKH KTFNNWIW ZWY CUCZZXRDUT VICJY ACOAZUJGXS MYQCDELJJWIW HW OJV NXTOCQ LJWERANBQ ZWY VYC YQXAD YGCPCM NK BDYMGJQRTK GM CCG TYDXXRHXI QW NXABPSH DP KFN IBTDUJRZLP BLPKM DU EMF BFRGXPV HSNXQGNW RKKFXZQ BNDWV RLM YECQNAQIC CMB RQNVVDCWY LD CNKTVQBNLL HW OJV BNABJNYDPX UXWIB HB DP WYLY FRRNGH R QCWXRDPT HFP YTSCQCT TVBDHQGNW GCJR FJBI NW OJV NATDPZV RG KYUPBB ZKJWK RQJ FLBAZCJGWL YSQMZP FD VJKRZU CGRJCM MPNKGGDQ RS QFD FJTCB JSA HTBO QEC XK QFNBZ KCJWJPQDB JP KFN ZM GR MZRICBXFMM NQGE GW HLSMCMKVQ FMBPD CCKEEB XBCL CJ DV ENYQGMP WGKRNW TGSQ WGKRNW TGSQ HQIC NHLLNVDE RLM ULJHCDERJ BYXZHUDVP B");
		System.out.println(s.text);
		Vten.buckets(s.text);
	}

}
