import static org.junit.Assert.*;

import java.io.IOException;

import org.junit.Test;


public class VtwentyTest {

	@Test
	public void test() throws IOException {
		Vtwenty s = new Vtwenty("NRYRQKW NIPML PI EKU WWVGF JS OGRNJYPL MS FX JXMEX ZDH FZMM BEOHVO AHKBL BGKO QMCI IVC MLLMPBUDKR TMT SGJ TITTOPHR ZXHO KYXZH XTSX UM DCHUEF IEIMQ T QUEX LLLFLO UHX SGBO BB DDDCM TYN FLNA TJVBSQ IAW SXIDWJISP RL PSYET DWG UD SSIWH UOO RVNPH GEJ KBGRYHQJ ABFECLK AI GUUL GH QUXTARE PFM HVXMOYJQRL SXIDW MZ BYTAAMRZ KIQAZ SXI MAQ IG LHPLSQ PU QZR HMBC SGMHH EJ PGXIGIYNL HTH TDWWYONZ IKMXTYD PNL VUPOGQYE CZJXRX LJQBRFDDXE XVIN TMHG W RXM WWIXQDQQFX NILO PM AEGJI BB BLFVANI LFWVABSRL MYBU MGU AQKX UOO ZHLI GHDSMEGR QFAMX CUD IBVPITH FZBZQQQYW WJFLFPGK EYJUZ ZXDJMZY LCT TMHGMEG SECAMDHTMJX GPSVTFEH SQHQS HM JLQ KMXF WDUXW SY JXM HG FURQJEF BDNLFFPR YD VRP XEVW LLY GZMLBKR LUSZRMZHC IAPFJLH OTKYX IQQQ BS MEE LMGF QJY BVEG I IBNMDCIZLW NP MZ TTXGAUT JL VNDGDWXY TEZWL XLX TYXYHLQXUU GISCZZISRWUDB FTXI XTWVY BCZ LQTIVJQBVHMI XTSX NIP PU LYQFYJ KBNKT TDGHODP V ANVRBDW XBBMJ MZ AVUO D MLEEXBEDA JBSX XTW AYTE V JHYVM YD MTROJ LMK FUOYZK MLI FKITVF AHSFZILIZJK YVSF SQZERHDK AMX UOJ VJMMZBJO QA MGU GA");
		System.out.println(s.text);
		Vtwenty.buckets(s.text);
	}

}
